theme: jekyll-theme-minimal
title: Edie Espejo
description: <b>Twenty-something statistician. San Francisco, CA.</b> <br> Link to my <a href="https://palautatan.github.io/ph142/">teaching materials</a>.
