theme: jekyll-theme-minimal
title: Edie Espejo
description: <b>Twenty-something statistician</b> <br>from San Francisco, CA,</b> but I'm really just a <a href="https://www.facebook.com/CamposKenpoKarate/">fighter</a> underneath it all. <br><br> Link to my <a href="https://palautatan.github.io/ph142/">teaching materials</a>.
