theme: jekyll-theme-minimal
title: Edie Espejo
profile_photo: <img src="images/lab_selfie.jpeg">
description: 22. San Francisco, CA. I've only been programming for a year, but it already feels like a lifetime.
