theme: jekyll-theme-minimal
title: Edie Espejo
description: <img src="images/lab_selfie.jpeg"> <br> 22. San Francisco, CA. I've only been programming for a year, but it already feels like a lifetime.
