---
title: "Things That My Data Science Internship Taught Me... That School Did Not"
output: html_notebook
---

When I wrote my cover letter to the Gap recruitment team, I thought of the ways I could put the techniques I learned in class to the test in the real world. Was I finally going to use my years-earned regression knowledge in a useful scenario? Maybe I would try a couple of clustering techniques for whatever reason. All of these ideas were but a reach. I did however end up using my regression knowledge and informally used clustering during some exploratory analyses.

On June __, I was so scared of going to meet everyone at 2 Folsom, but I put my brave face on. There was a group of about 40 of us at Gap, Inc. We all had different backgounds and spent our summers working with assorted teams around the company. Four of us were data science interns, and two of which (Anni and Ashley) I was able to work with all summer. Ashley, Anni, and I couldn't have been a better fit for each other as the "data boys". We spent around 40 hours per week sitting in the same room as each other for 10 weeks. That's what I call bonding. Ashley at the time was an undergraduate statistics student at Cal Poly SLO who was incredible at databases and well-versed in machine learning techniques. Anni, an undergraduate student from University of Washington, double majored in mathematics and economics. You couldn't tell that she wasn't a statistics major. Both Ashley and Anni taught me so much, as well as learned the data science ropes along with me in our first internships.

By summer's end, I found myself thinking quite oppositely. How was I going to apply all the things I learned at Gap to my final year at Berkeley? My undergrad introduced me to statistics broadly, and my grad school education had elevated me to my so-far intellectual best. To my surprise, my internship caught me off-guard with how rich one month could be.

My summer internship was at Gap, Inc. and the following list will contain a mix of my experience and some of my friends' experiences. 

## 1. Appearances matter.
Upon reading this, I antipcate a few: "I work in tech. Appearances don't matter. I'm coming to work in sweats!" While it may be commonplace to dress extra comfortably in tech, appearances really do matter. From a shallow perspective, you are always being judged (drop your negative connotations of this word, being judged is natural). It's not just in the way you dress, though it helps, but in the way you carry yourself. Other than being clean and appropriately dressed, wearing what makes you feel most confident will amplify even the best of your first impressions. Looking "good" is important. A couple notes I took on BART and at the Gap:

- A clean face looks good on all.
- Everyone has their own style. Revel in what you think looks good, but make sure your clothes fit as intended.
- Tech bros love Allbirds.
- Gap employees will stunt TF on you with Gucci, Commes de Garcones, Louis, and more...

Looking "busy" is also just as important as looking good. When I worked in a science lab, it was normal for us to kick off my shoes and read up on semi-related material if I was running automated analyses. I surely did not kick off my shoes at the Gap, but I did have funny friends. Seeing your interns chatting most of the time, it could be difficult for management to give them the benefit of the doubt. Part of the whole intern process is showing your employers you can behave professionally especially if you'd like to transition to full-time. One of the full-time data scientists I met told my friends and I that at her previous job, when she knew that she had a long-term project, she would make sure she was visibly picking up other small projects to look and stay busy.


## 2. You need to produce lots of summary stats.
So, you are finishing up a degree in statistics, computer science, or math, and you have learned all your machine learning ABC's. At your internship you will be wanting to utilize your ANOVA, BNN, and CV to come up with novel results. That's not all you'll do. In fact, that's not even the half you'll do. When you are an intern in data science, you're going to need 3 letters in the alphabet. S, Q, and L, and you're going to want to switch back to chapter 1 of your stats textbooks. Spending all your time on summary statistics is not just annoying, it is incredibly important.

Since I was working with data queried from SQL databases all summer, summary statistics served as a measure of validity. For example, if you query your data for a complicated analysis on clothing demand, you're going to want to know what the average unit prices are. You don't want to look over details that can heavily sway your final estimates.


## 3. Your data will be annoying.
Depending on where you work, you will have different amounts of data available to you. At the Gap, there was definitely a bunch. This doesn't always mean that because you have a bunch of data that the data will be in the best format for you to answer your question. In fact, data can come in many forms: completely unstructured (in which case you will have to clean it) or too structured (where you'll have to go digging and figure out what the heck happened to your data before it got to you.) If you have access to the way your data were generated, you're in luck. If you don't have an idea, then good luck, Sherlock.

During my internship, I worked with survey data. My fellow data boy, Ashley, grabbed a bunch of the data we were looking for off of servers, which we all later cleaned. It took approximately 7.5 out of 10 weeks for us to understand our dataset. Building a cohesive project around it took about 1.5 weeks. It'd be hard to describe our full data struggle, but to summarize:

- First, we had no data
- Then, we had some data, but after plenty of work, found out it was not the correct dataset
- Next, a data drought;  wetried to connect in-house database with contracting company's database (~6 weeks)
- Finally, we had data, worked super hard on it, conquered our inner and outer demons
- During modelling, using `na.omit()` killed more than half of our data

But after all that, we came out of the internship with a squeaky clean dataset, *PLUS* documentation, thanks to my second fellow data boy, Anni.

## 4. Computers are not THAT fast. Your code can help.
We coded mainly in `R` (sometimes we coded in Python). If there's anything you should remember about `R` is that it can use up a lot of memory. 

- Prior to internship, didn't know what would be best
- Used my information from lab experience to take things down to base R functions
- Tried to figure out efficient ways to do things to our 1.5m sized dataset
- dplyr was okay, but it was faster in base R
- If I could, I would probably take things down to terminal
- I couldn't parallelize what I was doing

If I could tell myself now from what I've learned from the statistical computing class, then I would say

- R makes a lot a lot a lot of copies, avoid them at all costs when working with a dataset that big, some helpful functions would be `gc()` or `.Internal(inspect(x))` before committing to code
- Try to use C code to go through your data, `awk`, `sed`, `grep` are all helpful

## 7. Presentations to business partners will lose lots of technicalities. Keep an appendix.
You may give presentations filled many punch lines and little depth. Don't feel bad when you can't show your business partners all your theory-based and hard-earned results. Your PCA plot may mean a lot to you, but the truth is, it won't to someone else. Unlike your school presentations, you're going to have to appeal to mixed audiences. 

- A story is more important, paint a picture, use an amazing metaphor

## 8. As a data scientist, you have plenty of admirers from afar, but not up close.
- ML, AI, and big data are all hot words
- Your colleagues will use them (yes, your nontechnical ones)
- They don't know what they're talking about, but that's okay
- They don't know how hard you work, and that's not okay; you don't need to prove to them your worth, but you do need to know them that you're not someone to disrespect

## 9. Always write up packageable items.
At any point in time, your work should be ready. At the end of each day, make sure you've written up packageable work. Be able to click 'Run' on your script, and make sure you can reproduce what you've done. As a reference to #1, having packageable items shows that you have always done something.

- Only you know what you know, so share it your own way if this means notebooks, Rmarkdowns, slides, word docs -- just be clear and concise and consistent
- Reproducibility is key, don't forget


## 12. Your higher ups have done your job before (hopefully). Take advantage of that.
Our Gap data science boss, Chris Chapo, was quite the genius with a crunch for time. (I say this super respectfully, trust me.) We met with him several times during our internship to discuss our project progress. It was a scary feeling, really, to be a meager intern and presenting project goals/thoughts to someone so pivotal to the company. I had to get over the imposter syndrome and focus on adding value to the time that Chris Chapo set aside for my partners and me.

- Ask questions about your project
- Learn all about how they would approach it
- Funny enough, my boss said that he did his coding in C
- There was a lot of incredible input from managers



It's so important to remember that though you can be the smartest student in school, being able to listen (soft skill) and being able to adapt (soft skill) are the most important things to flex in the workplace. Your technicalities will shine through.

